Fix build if linux/magic.h is not there
We only require one single define, and this one is already
in the code. So let's just move it to ploop.h file.

Fix the following build problem:

check.c:32:25: error: linux/magic.h: No such file or directory
check.c: In function 'ploop_check_delta':
check.c:456: error: 'EXT4_SUPER_MAGIC' undeclared (first use in this
function)
check.c:456: error: (Each undeclared identifier is reported only once
check.c:456: error: for each function it appears in.)
make[1]: *** [check.o] Error 1

Introduced in commit 73b16c4.

Signed-off-by: Kir Kolyshkin <kir@openvz.org>