ploop_resize_image(): fix compiler warning
    ploop.c: In function 'ploop_resize_image':
    ploop.c:1626:6: error: 'new_fs_size' may be used uninitialized in this function [-Werror=maybe-uninitialized]
    ploop.c:1663:8: note: 'new_fs_size' was declared here

Introduced by commit b8fbdad

Signed-off-by: Kir Kolyshkin <kir@openvz.org>