do_lock(): open file in read/write mode
Apparently, flock(LOCK_EX) requires a read/write opened file descriptor
in order to succeed on NFSv4.

This should fix the following error trying to use ploop on NFSv4 share:

	Error in do_lock (lock.c:136): Error in
	flock(<....>/DiskDescriptor.xml.lck): Bad file descriptor

https://bugzilla.openvz.org/2730

Reported-by: Pavel Odintsov <pavel.odintsov@gmail.com>
Signed-off-by: Kir Kolyshkin <kir@openvz.org>