Fix compile with musl wrt offsetof
offsetof() is defined in stddef.h, which is probably included
from some other includes in GNU libc, but not in musl libc, so
we get a number of errors like this:

 balloon_util.c:45:12: error: implicit declaration of function 'offsetof'
 [-Werror=implicit-function-declaration]

To fix, add the proper #include.

This fixes compilation for Alpine Linux.

Signed-off-by: Kir Kolyshkin <kir@openvz.org>