detect_image_sector_size(): compilation fix
This is a fix to recent commit r975730, to which compiler says:

	gpt.c: In function ‘detect_image_sector_size’:
	gpt.c:375:6: error: variable ‘xxx_sector_size’ set but not used
	[-Werror=unused-but-set-variable]
	cc1: all warnings being treated as errors

Signed-off-by: Kir Kolyshkin <kir@openvz.org>