tools/ploop-grow.c: remove unused vars
Apparently newer gcc version (4.6.2) added a new check for unused but set variable.
It chokes on the code with the following warning:

ploop-grow.c: In function ‘grow_delta_offline’:
ploop-grow.c:61:19: error: variable ‘new_l1_size’ set but not used [-Werror=unused-but-set-variable]
ploop-grow.c:61:6: error: variable ‘old_l1_size’ set but not used [-Werror=unused-but-set-variable]
cc1: all warnings being treated as errors

It's some remains of the old debug code, so removing.

Signed-off-by: Kir Kolyshkin <kir@openvz.org>