get_max_ploop_size(): change type of last arg
Use "unsigned long long" as a portable type, to fix the following
compilation error on POWER (caused by the fact that __u64 is defined
as "unsigned long" on POWER, but "unsigned long long" on x86_64).

> ploop.c: In function ‘ploop_get_max_size’:
> ploop.c:305:2: error: passing argument 3 of ‘get_max_ploop_size’ from incompatible pointer type [-Werror]
>   if (get_max_ploop_size(default_fmt_version(), blocksize, max))
>   ^
> ploop.c:275:12: note: expected ‘long unsigned int *’ but argument is of type ‘long long unsigned int *’
>  static int get_max_ploop_size(int version, unsigned int blocksize, __u64 *max)
>             ^
>

Signed-off-by: Kir Kolyshkin <kir@openvz.org>