lib/gpt.c: compile fix
This is a compilation fix to commit r975730, which adds

	#include <linux/fs.h>

statement. Apparently, already included <sys/mount.h> have all the same
defines, therefore it gives a multitude of errors, like these:

	In file included from gpt.c:30:0:
	../include/linux/fs.h:27:0: error: "BLOCK_SIZE" redefined [-Werror]
	In file included from gpt.c:28:0:
	/usr/include/sys/mount.h:27:0: note: this is the location of the
	previous definition
	In file included from gpt.c:30:0:
	../include/linux/fs.h:208:0: error: "MS_RDONLY" redefined [-Werror]
	In file included from gpt.c:28:0:
	/usr/include/sys/mount.h:36:0: note: this is the location of the
	previous definition

NOTE: this is on Fedora 18 system. I will recheck on CentOS 5 and 6
later and fix if necessary.

Signed-off-by: Kir Kolyshkin <kir@openvz.org>