Fix a few 'result unused' compiler warnings
Like this one, emitted by clang:

balloon.c:426:3: error: expression result unused [-Werror,-Wunused-value]
                ioctl_device(fd, PLOOP_IOC_BALLOON, &b_ctl);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Kir Kolyshkin <kir@openvz.org>